---
title: Fronenesia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: farishanugraha@gmail.com
description: Fronenesia adalah tempat berbagi tulisan seputar dunia Front End Web
  Development, dalam bahasa Indonesia. Kritik dan saran dapat dikirim ke farishanugraha@gmail.com
baseurl: 
url: 
twitter_username: farishanugraha
github_username: farishan
theme: minima
plugins:
- jekyll-feed
- jekyll-admin
